// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2wCRPDMA9p-jlshF2Ih2sr6R7RkyEUGI',
    appId: '1:442319896533:web:16e098f12bdec948b9475c',
    messagingSenderId: '442319896533',
    projectId: 'study-app-21b19',
    authDomain: 'study-app-21b19.firebaseapp.com',
    storageBucket: 'study-app-21b19.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_lJS9whLWSwETAnESCGlTbMgeu449Po',
    appId: '1:442319896533:android:0c5a0df50841822fb9475c',
    messagingSenderId: '442319896533',
    projectId: 'study-app-21b19',
    storageBucket: 'study-app-21b19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXJ2Z4vQMipyY_vh7bU7Oh9SF5Lnf4v5Q',
    appId: '1:442319896533:ios:f12fe4d9ba2ab259b9475c',
    messagingSenderId: '442319896533',
    projectId: 'study-app-21b19',
    storageBucket: 'study-app-21b19.appspot.com',
    iosClientId: '442319896533-fe0gv0rkdfk4aohjk4rvtfoqtqv28hdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXJ2Z4vQMipyY_vh7bU7Oh9SF5Lnf4v5Q',
    appId: '1:442319896533:ios:f12fe4d9ba2ab259b9475c',
    messagingSenderId: '442319896533',
    projectId: 'study-app-21b19',
    storageBucket: 'study-app-21b19.appspot.com',
    iosClientId: '442319896533-fe0gv0rkdfk4aohjk4rvtfoqtqv28hdo.apps.googleusercontent.com',
    iosBundleId: 'com.example.studyApp',
  );
}
